influxdb:
  image: codenamekt/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"

telegraf:
  image: codenamekt/telegraf
  links:
   - influxdb

chronograf:
  image: codenamekt/chronograf
  ports:
    - "9080:9080"
  links:
   - influxdb
